(source (git https://github.com/ocaml-templates/spin-reason-c-bindings.git))
(config username "Alain Armand")
(config project_name fzy_bindings)
(config email aarmand.inbox@gmail.com)
(config npm_username idkjs)
(config github_username idkjs)
(config project_description
 "A short, but powerful statement about your project")
(config package_manager Esy)
(config ci_cd Github)
(config syntax Reason)
(config project_snake fzybindings)
(config project_slug fzybindings)
(config test_framework Rely)
